#!/bin/bash
source /opt/ros/humble/setup.bash
# Launch lane contours
echo 'RUNNING: contours'
ros2 run lane_detection contours > contour.log &

# Launch IPM
echo 'RUNNING: IPM'
ros2 run multicamera ipm &

# Launch image drawer
echo 'RUNNING: IMAGE DRAWER'
ros2 run lane_detection image_drawer > image_drawer.log &

# Launch lane processing
#echo 'RUNNING: LANE PROCESSING'
#ros2 run lane_detection lane_logic &

# Wait for all background processes to complete
wait
